# Generated by Django 4.0.1 on 2022-01-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_vehicle_last_datetime_vehicle_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='last_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='last_longitude',
            new_name='longitude',
        ),
    ]
